user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzM0MzY=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.Ln7s6yHp_JR3WaTAGgouXIXjK8JHM2q6GWfKL-YwVOEqB9irFTg0BVOe4uyncKCe7Ungo1OSy2cAQwSZoSaME1weUjdyQVDks348MkRQrctnujnP888UzsV2YHuZzYfgirnZ4CK4kIaa4QwFuw6-8owzar0JEXqRH6J1Ij2sLEisN4Ebg16qxZWBeZsmS68Q
  group_id: 205115018


