"""Add new models

Revision ID: 1cc370681a71
Revises: 333527a1553b
Create Date: 2022-09-20 10:34:13.776436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cc370681a71"
down_revision = "333527a1553b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "statistics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("total_wins", sa.BigInteger(), nullable=True),
        sa.Column("total_losses", sa.BigInteger(), nullable=True),
        sa.Column("total_draw", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "current_game",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("queue", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.BigInteger(), nullable=True),
        sa.Column("cards", sa.String(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("vk_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("statistic_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["statistic_id"], ["statistics.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vk_id"),
    )
    op.create_table(
        "game_user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("cards", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("current_game_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_game_id"],
            ["current_game.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_user")
    op.drop_table("users")
    op.drop_table("current_game")
    op.drop_table("statistics")
    op.drop_table("chat")
    # ### end Alembic commands ###
